services:
  couchdb:
    image: apache/couchdb:2
  app:
    build: .
    ports:
      - 9012:8080
    environment:
      - DB_URL=http://couchdb:5984/
      - FLAG=testflag
    depends_on:
      - couchdb